### ISSUE TITLE
Outdated example

### ISSUE THREAD

**Issue by robbie1douglas** [Azure-Samples/container-instances-python-manage#5]
Hi,
I'm trying to use this example but am getting this error.

```
Traceback (most recent call last):
  File "example.py", line 122, in <module>
    main()
  File "example.py", line 36, in main
    list_container_groups()
  File "example.py", line 62, in list_container_groups
    for container_group in container_groups:
  File "/Users/rld244/cul/tests/container-instances-python-manage/src/venv/lib/python3.8/site-packages/msrest/paging.py", line 143, in __next__
    self.advance_page()
  File "/Users/rld244/cul/tests/container-instances-python-manage/src/venv/lib/python3.8/site-packages/msrest/paging.py", line 129, in advance_page
    self._response = self._get_next(self.next_link)
  File "/Users/rld244/cul/tests/container-instances-python-manage/src/venv/lib/python3.8/site-packages/azure/mgmt/containerinstance/operations/container_groups_operations.py", line 91, in internal_paging
    response = self._client.send(request, stream=False, **operation_config)
  File "/Users/rld244/cul/tests/container-instances-python-manage/src/venv/lib/python3.8/site-packages/msrest/service_client.py", line 336, in send
    pipeline_response = self.config.pipeline.run(request, **kwargs)
  File "/Users/rld244/cul/tests/container-instances-python-manage/src/venv/lib/python3.8/site-packages/msrest/pipeline/__init__.py", line 197, in run
    return first_node.send(pipeline_request, **kwargs)  # type: ignore
  File "/Users/rld244/cul/tests/container-instances-python-manage/src/venv/lib/python3.8/site-packages/msrest/pipeline/__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File "/Users/rld244/cul/tests/container-instances-python-manage/src/venv/lib/python3.8/site-packages/msrest/pipeline/requests.py", line 65, in send
    self._creds.signed_session(session)
AttributeError: 'ClientSecretCredential' object has no attribute 'signed_session'
(venv) lib-rld244-maclap:src rld244$ python3 example.py
Traceback (most recent call last):
  File "example.py", line 122, in <module>
    main()
  File "example.py", line 42, in main
    resource_client.resource_groups.create_or_update(
  File "/Users/rld244/cul/tests/container-instances-python-manage/src/venv/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 73, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/Users/rld244/cul/tests/container-instances-python-manage/src/venv/lib/python3.8/site-packages/azure/mgmt/resource/resources/v2021_04_01/operations/_resource_groups_operations.py", line 405, in create_or_update
    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
  File "/Users/rld244/cul/tests/container-instances-python-manage/src/venv/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/Users/rld244/cul/tests/container-instances-python-manage/src/venv/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/Users/rld244/cul/tests/container-instances-python-manage/src/venv/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/Users/rld244/cul/tests/container-instances-python-manage/src/venv/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "/Users/rld244/cul/tests/container-instances-python-manage/src/venv/lib/python3.8/site-packages/azure/mgmt/core/policies/_base.py", line 47, in send
    response = self.next.send(request)
  File "/Users/rld244/cul/tests/container-instances-python-manage/src/venv/lib/python3.8/site-packages/azure/core/pipeline/policies/_redirect.py", line 158, in send
    response = self.next.send(request)
  File "/Users/rld244/cul/tests/container-instances-python-manage/src/venv/lib/python3.8/site-packages/azure/core/pipeline/policies/_retry.py", line 445, in send
    response = self.next.send(request)
  File "/Users/rld244/cul/tests/container-instances-python-manage/src/venv/lib/python3.8/site-packages/azure/core/pipeline/policies/_authentication.py", line 117, in send
    self.on_request(request)
  File "/Users/rld244/cul/tests/container-instances-python-manage/src/venv/lib/python3.8/site-packages/azure/core/pipeline/policies/_authentication.py", line 94, in on_request
    self._token = self._credential.get_token(*self._scopes)
AttributeError: 'ServicePrincipalCredentials' object has no attribute 'get_token'
```
When I try what I found here https://stackoverflow.com/questions/64063850/azure-python-sdk-serviceprincipalcredentials-object-has-no-attribute-get-tok I get this error.
```
Traceback (most recent call last):
  File "example.py", line 122, in <module>
    main()
  File "example.py", line 36, in main
    list_container_groups()
  File "example.py", line 62, in list_container_groups
    for container_group in container_groups:
  File "/Users/rld244/cul/tests/container-instances-python-manage/src/venv/lib/python3.8/site-packages/msrest/paging.py", line 143, in __next__
    self.advance_page()
  File "/Users/rld244/cul/tests/container-instances-python-manage/src/venv/lib/python3.8/site-packages/msrest/paging.py", line 129, in advance_page
    self._response = self._get_next(self.next_link)
  File "/Users/rld244/cul/tests/container-instances-python-manage/src/venv/lib/python3.8/site-packages/azure/mgmt/containerinstance/operations/container_groups_operations.py", line 91, in internal_paging
    response = self._client.send(request, stream=False, **operation_config)
  File "/Users/rld244/cul/tests/container-instances-python-manage/src/venv/lib/python3.8/site-packages/msrest/service_client.py", line 336, in send
    pipeline_response = self.config.pipeline.run(request, **kwargs)
  File "/Users/rld244/cul/tests/container-instances-python-manage/src/venv/lib/python3.8/site-packages/msrest/pipeline/__init__.py", line 197, in run
    return first_node.send(pipeline_request, **kwargs)  # type: ignore
  File "/Users/rld244/cul/tests/container-instances-python-manage/src/venv/lib/python3.8/site-packages/msrest/pipeline/__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File "/Users/rld244/cul/tests/container-instances-python-manage/src/venv/lib/python3.8/site-packages/msrest/pipeline/requests.py", line 65, in send
    self._creds.signed_session(session)
AttributeError: 'ClientSecretCredential' object has no attribute 'signed_session'
```

**Comment by robbie1douglas** [comment]
Also would it be possible to get the minimum permissions required to run this?
